apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    strategy.spinnaker.io/max-version-history: '3'
    traffic.spinnaker.io/load-balancers: '["service sample-backend-api-service"]'
  labels:
    app: sample-backend-api-deploy
  name: sample-backend-api-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-backend-api
  template:
    metadata:
      labels:
        app: sample-backend-api
    spec:
      containers:
        - image: harbor.misoboy.kr/sample-backend/sample-backend-app:${parameters.imageTag}
          name: sample-backend-api
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/v1/user/
              port: 8080
      imagePullSecrets:
        - name: harbor-misoboy-registry
